[phases.setup]
# Install python3 and ffmpeg
nixPkgs = ["python3.11", "ffmpeg"]

[phases.install]
cmds = [
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = []

[phases.start]
cmd = "python music_bot.py"
