[phases.setup]
# We need python + pip + ffmpeg so Nixpacks can use them
nixPkgs = ["python3.11Full", "ffmpeg"]

[phases.install]
# After Nixpacks installs python and pip, we can install from requirements.txt
cmds = [
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = []

[phases.start]
# The command to run your bot
cmd = "python music_bot.py"
